
name: 'models_metadata_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "dbt_modules"

on-run-end:
  - 'drop view integration_tests_postgres.verify;'